include = ["streamsnapper/*.py", "streamsnapper/platforms/*.py", "tests/*.py"]
exclude = [".venv", "__pycache__", ".ruff_cache"]
target-version = "py313"
line-length = 130
indent-width = 4

[lint]
fixable = ["ALL"]
unfixable = []
select = ["E4", "E7", "E9", "F"]
ignore = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
